###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=agenda
            - MYSQL_USER=agenda
            - MYSQL_PASSWORD=agenda123
        command:
            --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        ports:
            - '37002:3306'
        networks:
            - agenda_websocket

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '37000:80'
            - '37001:37001'
        networks:
            - agenda_websocket
    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './backend:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
        networks:
            - agenda_websocket
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        ports:
            - '37003:80'
        environment:
            - PMA_ARBITRARY=1
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - agenda_websocket
networks:
  agenda_websocket:
