name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_ZONE: ${{ secrets.GCP_ZONE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Iniciando Docker-compose
      run: |
        docker-compose up -d

    - name: Rodando Validacao de Codigo
      run: |
        docker-compose run --rm php-fpm composer install
        docker-compose run --rm php-fpm composer cs-check
        docker-compose run --rm php-fpm composer analyze
    - name: Rodando Teste Unitario
      run: |
        docker-compose run --rm php-fpm vendor/bin/phpunit --colors=always --do-not-cache-result