name: Build and Deploy

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Iniciando Docker-compose
      run: |
        docker-compose up -d

    - name: Rodando Validacao de Codigo
      run: |
        docker-compose run --rm php-fpm composer install
        docker-compose run --rm php-fpm composer cs-check
        docker-compose run --rm php-fpm composer analyze
    - name: Rodando Teste Unitario
      run: |
        docker-compose run --rm php-fpm vendor/bin/phpunit --colors=always --do-not-cache-result

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Instalando Componente Vue.js
      run: |
      cd frontend
      npm install

    - name: Gerando Build do front end
      run: |
      cd frontend
      npm run build