name: Deploy to GCE

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_ZONE: ${{ secrets.GCP_ZONE }}
      GCP_SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      run: |
        echo "$GCP_SA_KEY"
        echo "$GCP_SA_KEY" > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project $GCP_PROJECT_ID
        gcloud config set compute/zone $GCP_ZONE

    - name: Set environment variables
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        export SECRET_KEY=${GCP_SECRET_KEY}

    - name: Deploy to GCE
      run: |
        # Seu comando de deploy aqui
        gcloud compute scp --project="${GCP_PROJECT_ID}" --zone="${GCP_ZONE}" --recurse * mauricio_rsc_mg@instance-1-testapatricococo:./
        gcloud compute ssh mauricio_rsc_mg@instance-1-testapatricococo --project="${GCP_PROJECT_ID}" --zone="${GCP_ZONE}" --command "docker --version"
